### ISSUE TITLE
IAKI Set Starting ID for importing Images

### ISSUE THREAD

**Issue by pswgroup** [getk2/k2-iaki#1]
I'd like to suggest the following update/fix/enhancement to the IAKI plugin.

in joomlasite\plugins\k2\jw_iaki\jw_iaki.php:

// Get the K2 plugin params

$limitK2ItemIdStart                 = (int) $pluginParams->get('limitK2ItemIdStart');
        $limitK2ItemIdEnd                   = (int) $pluginParams->get('limitK2ItemIdEnd');

// Output
        if($item->id>=$limitK2ItemIdStart && $item->id<=$limitK2ItemIdEnd){
...
}

in joomlasite\plugins\k2\jw_iaki\jw_iaki.xml:

< fieldset name="basic" >
                < field name="limitK2ItemIdStart" type="text" size="6" default="" label="JW_PLG_IAKI_LIMITK2ITEMID_START" description="" />
                < field name="limitK2ItemIdEnd" type="text" size="6" default="" label="JW_PLG_IAKI_LIMITK2ITEMID_END" description="" />
...
</ fieldset >

and in joomlasite\administrator\language\en-GB\en-GB.plg_k2_jw_iaki.ini

JW_PLG_IAKI_LIMITK2ITEMID_START="K2 item ID (starting from)"
JW_PLG_IAKI_LIMITK2ITEMID_END="K2 item ID (up to which we limit the import)"

We tested this solution on Joomla! v2.5.14, K2 v2.6.7 and IAKI v2.0 and it works.

Thanks,
Adel / PSW Group

**Comment by fevangelou** [comment]
Noted to be added in an upcoming release.
